#!/bin/bash
sudo apt install python3-pip
export PATH=/usr/local/bin:$PATH
sudo pip3 install virtualenv
cd /home/ec2-user/app
sudo chown -R ec2-user /home/ec2-user/app
virtualenv environment
source environment/bin/activate
sudo pip3 install -r requirements.txt
